#!/usr/bin/env bash

# --- AI NOTICE ---
# This script was generated by a large language model. Please read ./AI_USAGE for more info.

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SPEC="$PROJECT_DIR/packaging/dustbunny.spec"

RPMBUILD="$HOME/rpmbuild"
SPEC_DEST="$RPMBUILD/SPECS/dustbunny.spec"
RPM_DIR="$RPMBUILD/RPMS/x86_64"
SOURCE_DIR="$RPMBUILD/SOURCES"

REPO_DIR="$HOME/Projects/dot-underscore1703.github.io"
REPO_ARCH="$REPO_DIR/x86_64"

PACKAGE="dustbunny"

VERSION="$(awk '$1 == "Version:" {print $2; exit}' "$SPEC")"
RELEASE="$(awk '$1 == "Release:" {print $2; exit}' "$SPEC" | sed 's/%{?dist}//')"

if [[ -z "$VERSION" ]]; then
    echo "ERROR: Could not determine package version."
    exit 1
fi

if [[ -z "$RELEASE" ]]; then
    echo "ERROR: Could not determine package release."
    exit 1
fi

echo "==> Releasing $PACKAGE $VERSION-$RELEASE"

echo "==> Preparing rpmbuild tree"

mkdir -p "$RPMBUILD/SPECS"
mkdir -p "$SOURCE_DIR"
mkdir -p "$RPM_DIR"
echo "==> Installing spec into rpmbuild tree"

cp "$SPEC" "$SPEC_DEST"

echo "==> Creating source archive"

SOURCE_ARCHIVE="$SOURCE_DIR/${PACKAGE}-${VERSION}.tar.gz"

rm -f "$SOURCE_ARCHIVE"

git -C "$PROJECT_DIR" archive \
    --format=tar.gz \
    --prefix="${PACKAGE}-${VERSION}/" \
    -o "$SOURCE_ARCHIVE" \
    HEAD

if [[ ! -f "$SOURCE_ARCHIVE" ]]; then
    echo "ERROR: Failed to create source archive:"
    echo "       $SOURCE_ARCHIVE"
    exit 1
fi

echo "    $SOURCE_ARCHIVE"

echo "==> Cleaning old build artifacts"

rm -rf "$RPMBUILD/BUILD/${PACKAGE}-"* \
       "$RPMBUILD/BUILDROOT/${PACKAGE}-"* \
       "$RPMBUILD/RPMS/x86_64/${PACKAGE}-"* \
       "$RPMBUILD/SRPMS/${PACKAGE}-"*

echo "==> Building RPM"

rpmbuild -ba "$SPEC_DEST"

RPM="$RPM_DIR/${PACKAGE}-${VERSION}-${RELEASE}.fc44.x86_64.rpm"

if [[ ! -f "$RPM" ]]; then
    echo "ERROR: Expected RPM was not produced:"
    echo "       $RPM"
    exit 1
fi


echo "==> Verifying RPM"

RPM_VERSION="$(rpm -qp --qf '%{VERSION}-%{RELEASE}.%{ARCH}\n' "$RPM")"

echo "    $RPM_VERSION"

EXPECTED_RPM_VERSION="$VERSION-$RELEASE.fc44.x86_64"

if [[ "$RPM_VERSION" != "$EXPECTED_RPM_VERSION" ]]; then
    echo "ERROR: RPM version does not match spec."
    echo "       Expected: $EXPECTED_RPM_VERSION"
    echo "       Got:      $RPM_VERSION"
    exit 1
fi
echo "==> Verifying binary"

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

cd "$TMP_DIR"

rpm2cpio "$RPM" | cpio -idm >/dev/null 2>&1

BINARY="./usr/bin/dustbunny"

if [[ ! -f "$BINARY" ]]; then
    echo "ERROR: RPM does not contain /usr/bin/dustbunny"
    exit 1
fi

if [[ ! -x "$BINARY" ]]; then
    echo "ERROR: /usr/bin/dustbunny is not executable"
    exit 1
fi

echo "    Found executable: /usr/bin/dustbunny"

# Verify that it is an ELF executable.
if ! file "$BINARY" | grep -q "ELF"; then
    echo "ERROR: /usr/bin/dustbunny is not an ELF executable"
    exit 1
fi

echo "    ELF executable verified"

echo "==> Publishing RPMs"

mkdir -p "$REPO_ARCH"

cp "$RPM" "$REPO_ARCH/"

DEBUGINFO_RPM="$RPM_DIR/${PACKAGE}-debuginfo-${VERSION}-${RELEASE}.fc44.x86_64.rpm"
DEBUGSOURCE_RPM="$RPM_DIR/${PACKAGE}-debugsource-${VERSION}-${RELEASE}.fc44.x86_64.rpm"

if [[ -f "$DEBUGINFO_RPM" ]]; then
    cp "$DEBUGINFO_RPM" "$REPO_ARCH/"
fi

if [[ -f "$DEBUGSOURCE_RPM" ]]; then
    cp "$DEBUGSOURCE_RPM" "$REPO_ARCH/"
fi


echo "==> Regenerating repository metadata"

cd "$REPO_ARCH"

createrepo_c --update .

cd "$REPO_DIR"

echo "==> Git status"

git status --short

echo
echo "Packages ready for release:"
echo "    $REPO_ARCH/${PACKAGE}-${VERSION}-${RELEASE}.fc44.x86_64.rpm"

if [[ -f "$DEBUGINFO_RPM" ]]; then
    echo "    $REPO_ARCH/${PACKAGE}-debuginfo-${VERSION}-${RELEASE}.fc44.x86_64.rpm"
fi

if [[ -f "$DEBUGSOURCE_RPM" ]]; then
    echo "    $REPO_ARCH/${PACKAGE}-debugsource-${VERSION}-${RELEASE}.fc44.x86_64.rpm"
fi


echo
read -rp "Commit and push release $VERSION-$RELEASE? [y/N] " answer

if [[ "$answer" != "y" && "$answer" != "Y" ]]; then
    echo "Release files are ready, but were NOT committed/pushed."
    exit 0
fi

git add x86_64/

git commit -m "Release $PACKAGE $VERSION"

git push

echo
echo "=========================================="
echo " Successfully released $PACKAGE $VERSION"
echo "=========================================="
